version: "3.9"

services:
  db:
    image: postgres:15
    container_name: webserver-db
    # Читаємо змінні з файлу в папці backend
    env_file:
      - ./backend/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: webserver-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # Читаємо той самий файл
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: webserver-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - webnet

  minio:
    image: minio/minio:latest
    container_name: webserver-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # Тут теж вказуємо шлях до backend/.env
    env_file:
      - ./backend/.env
    volumes:
      - minio_data:/data
    networks:
      - webnet

volumes:
  pg_data:
  minio_data:

networks:
  webnet: