version: "3.9"

services:
  db:
    image: postgres:15
    container_name: webserver-db
    env_file:
      - ./backend/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: webserver-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./html:/app/static
    networks:
      - webnet

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: webserver-npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - webnet

  minio:
    image: minio/minio:latest
    container_name: webserver-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env
    volumes:
      - minio_data:/data
    networks:
      - webnet

volumes:
  pg_data:
  minio_data:

networks:
  webnet: